#!/bin/sh
# Generates server/engine/web_engine.lua: a self-contained Luau file embedding
# the game modules (Config/CardDefs/Rules/Game), a JSON codec, and the WASM
# sidecar bridge. This is the artifact deployed to Render; the sibling
# uno-roblox repo is only needed when re-generating.
# Usage: sh server/engine/gen_bundle.sh
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="${UNO_SRC:-$(cd "$ROOT/../.." && pwd)/uno-roblox}"
OUT="$ROOT/engine/web_engine.lua"
cat > "$OUT" <<'EOF'
-- AUTOGENERATED by gen_bundle.sh -- do not edit.
-- Self-contained UNO web engine: game modules + JSON codec + WASM sidecar.
-- Loaded by the Node server inside the luau-web WASM VM.
local BUNDLE = {}
EOF
emit() {
  printf 'BUNDLE[%s] = [====[' "$(printf '"%s"' "$1")" >> "$OUT"
  printf '\n' >> "$OUT"
  cat "$2" >> "$OUT"
  printf '\n]====]\n' >> "$OUT"
}
emit "Config" "$REPO/src/ReplicatedStorage/UNO/Config.lua"
emit "CardDefs" "$REPO/src/ReplicatedStorage/UNO/CardDefs.lua"
emit "Rules" "$REPO/src/ReplicatedStorage/UNO/Rules.lua"
emit "Game" "$REPO/src/ServerScriptService/UNO/Game.lua"
emit "Json" "$ROOT/engine/json.lua"
cat "$ROOT/engine/bridge_body.lua" >> "$OUT"
echo "wrote $OUT"