-- AUTOGENERATED by gen_bundle.sh -- do not edit.
-- Self-contained UNO web engine: game modules + JSON codec + WASM sidecar.
-- Loaded by the Node server inside the luau-web WASM VM.
local BUNDLE = {}
BUNDLE["Config"] = [====[
local Config = {}

Config.MinPlayers = 2
Config.MaxPlayers = 8
Config.DefaultCapacity = 4

Config.StartingHandSize = 7
Config.TargetScore = 500

-- Timing (seconds, server-authoritative via workspace:GetServerTimeNow())
Config.TurnTime = 45
Config.PostDrawGrace = 12 -- extra time after drawing a playable card
Config.OpeningChoiceTime = 20
Config.UnoSelfCallWindow = 4
Config.Wild4ChallengeTime = 8
Config.RoundResultTime = 20 -- auto-continue after a round
Config.GameOverTime = 30 -- auto-return to lobby after a game ends

-- Scoring (official)
Config.ScoreKeepAt500 = false
-- true  = 2022 "first to go out" per round, winner is first go-out (TargetScore ignored)
-- false = classic: first to reach TargetScore wins
Config.WinByFirstOut = false

return Config
]====]
BUNDLE["CardDefs"] = [====[
local CardDefs = {}

CardDefs.Colors = { "Red", "Yellow", "Green", "Blue" }

-- Color3 exists inside Roblox; fall back to raw RGB tables outside it (tests).
local function rgb(r, g, b)
	if Color3 then
		return Color3.fromRGB(r, g, b)
	end
	return { r, g, b }
end

CardDefs.ColorHex = {
	Red = rgb(214, 41, 49),
	Yellow = rgb(255, 200, 0),
	Green = rgb(0, 128, 64),
	Blue = rgb(36, 90, 199),
	Black = rgb(24, 24, 28),
}

CardDefs.Kinds = { "number", "skip", "reverse", "drawtwo", "wild", "wilddrawfour" }

CardDefs.Glyphs = {
	skip = "SKIP",
	reverse = "REV",
	drawtwo = "+2",
	wild = "WILD",
	wilddrawfour = "+4",
}

local nextId = 0
local function newCard(kind, color, value)
	nextId = nextId + 1
	if kind == "number" then
		return { id = nextId, kind = kind, color = color, value = value }
	end
	return { id = nextId, kind = kind, color = color, value = value }
end

-- Official 108-card deck: per suit 1x of 0..9, 2x each 1..9/action; 4 Wild, 4 Wild Draw Four
function CardDefs.buildDeck()
	local deck = {}
	for _, color in ipairs(CardDefs.Colors) do
		for v = 0, 9 do
			local copies = 1
			if v > 0 then
				copies = 2
			end
			for _ = 1, copies do
				table.insert(deck, newCard("number", color, v))
			end
		end
		for _ = 1, 2 do
			table.insert(deck, newCard("skip", color, 0))
			table.insert(deck, newCard("reverse", color, 0))
			table.insert(deck, newCard("drawtwo", color, 0))
		end
	end
	for _ = 1, 4 do
		table.insert(deck, newCard("wild", nil, 0))
		table.insert(deck, newCard("wilddrawfour", nil, 0))
	end
	return deck
end

-- Is the discard top face-up vs face-down irrelevant here; we always keep cards with color nil meaning wild.
-- Wild cards never carry a color, matching official deck.

function CardDefs.cardName(card)
	if not card then
		return "?"
	end
	if card.kind == "number" then
		return card.color .. " " .. card.value
	end
	local glyph = CardDefs.Glyphs[card.kind] or card.kind
	if card.color then
		return card.color .. " " .. glyph
	end
	return glyph
end

function CardDefs.points(card)
	if not card then
		return 0
	end
	if card.kind == "number" then
		return card.value
	end
	if card.kind == "wild" or card.kind == "wilddrawfour" then
		return 50
	end
	return 20
end

return CardDefs
]====]
BUNDLE["Rules"] = [====[
local CardDefs = require(script.Parent.CardDefs)

local Rules = {}

-- A card is playable if it matches color, number, or symbol of the top card.
-- Wild cards are always playable.
function Rules.canPlay(card, topCard, currentColor)
	card = card or {}
	topCard = topCard or {}
	if card.kind == "wild" or card.kind == "wilddrawfour" then
		return true
	end
	if topCard.kind == "wild" or topCard.kind == "wilddrawfour" then
		-- After a wild, only color matters.
		return card.color == currentColor
	end
	if card.color == topCard.color then
		return true
	end
	-- Symbol match (drawtwo on drawtwo / reverse on reverse / skip on skip) or number match.
	if card.kind == topCard.kind then
		return true
	end
	if card.kind == "number" and topCard.kind == "number" and card.value == topCard.value then
		return true
	end
	return false
end

-- Wild Draw Four is only *supposed* to be played when you hold no card matching
-- the current color. Bluffing is allowed by official rules (penalty only if challenged).
function Rules.hasColorMatch(hand, color)
	for _, c in ipairs(hand) do
		if c.color == color then
			return true
		end
	end
	return false
end

function Rules.wildDrawFourLegal(hand, currentColor)
	return not Rules.hasColorMatch(hand, currentColor)
end

-- Fisher-Yates
function Rules.shuffle(list, rng)
	for i = #list, 2, -1 do
		local j = rng:NextInteger(1, i)
		list[i], list[j] = list[j], list[i]
	end
	return list
end

function Rules.totalPoints(hand)
	local total = 0
	for _, c in ipairs(hand) do
		total = total + CardDefs.points(c)
	end
	return total
end

return Rules
]====]
BUNDLE["Game"] = [====[
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Workspace = game:GetService("Workspace")

local Config = require(ReplicatedStorage.UNO.Config)
local CardDefs = require(ReplicatedStorage.UNO.CardDefs)
local Rules = require(ReplicatedStorage.UNO.Rules)

local Game = {}
Game.__index = Game

local function now()
	return Workspace:GetServerTimeNow()
end

local function validateColor(color)
	for _, c in ipairs(CardDefs.Colors) do
		if c == color then
			return true
		end
	end
	return false
end

-- players: list of { userId, name } (first becomes host)
-- remotes: { StateUpdate, Notice } RemoteEvents
function Game.new(players, remotes)
	local self = setmetatable({}, Game)
	self.rng = Random.new()
	self.remotes = remotes
	self.phase = "lobby"
	self.capacity = Config.DefaultCapacity
	self._noHostCheck = false
	self.players = {}
	for i, p in ipairs(players) do
		table.insert(self.players, {
			userId = p.userId,
			name = p.name,
			isHost = i == 1,
			hand = {},
			score = 0,
			unoCalled = false,
			catchable = false,
			connected = true,
		})
	end
	self.dealerIdx = 1
	self.direction = 1
	self.currentColor = nil
	self.topCard = nil
	self.deck = {}
	self.discard = {}
	self.currentIdx = nil
	self.hasDrawn = false
	self.drewCard = nil
	self.drawDeadline = 0
	self.pendingChallenge = nil
	self.openingPick = nil
	self.roundResult = nil
	self.gameResult = nil
	self.stateDeadline = 0
	return self
end

-- ------------------------- roster helpers -------------------------

function Game:findPlayer(userId)
	for i, p in ipairs(self.players) do
		if p.userId == userId then
			return i, p
		end
	end
	return nil
end

function Game:hostIdx()
	for i, p in ipairs(self.players) do
		if p.isHost then
			return i
		end
	end
	return #self.players >= 1 and 1 or nil
end

function Game:hostUser()
	local i = self:hostIdx()
	return i and self.players[i].userId or nil
end

function Game:step(i)
	local n = #self.players
	if n == 0 then
		return 0
	end
	local j = i + self.direction
	while j < 1 do
		j += n
	end
	while j > n do
		j -= n
	end
	return j
end

function Game:getLiveCount()
	local n = 0
	for _, p in ipairs(self.players) do
		if p.connected then
			n += 1
		end
	end
	return n
end

-- ------------------------- broadcast -------------------------

function Game:publicPlayer(p)
	return {
		userId = p.userId,
		name = p.name,
		score = p.score,
		cardCount = #p.hand,
		isHost = p.isHost,
		unoCalled = p.unoCalled,
		catchable = p.catchable,
	}
end

function Game:serializeFor(userId)
	local meIdx, me = self:findPlayer(userId)
	local players = {}
	for _, p in ipairs(self.players) do
		table.insert(players, self:publicPlayer(p))
	end
	local state = {
		phase = self.phase,
		capacity = self.capacity,
		hostUserId = self:hostUser(),
		players = players,
		me = meIdx and {
			userId = me.userId,
			hand = me.hand,
			isTurn = self.currentIdx ~= nil and self.currentIdx == meIdx,
			hasDrawn = self.hasDrawn,
		} or nil,
		turnUserId = self.currentIdx and self.players[self.currentIdx].userId or nil,
		direction = self.direction,
		currentColor = self.currentColor,
		topCard = self.topCard,
		deckCount = #self.deck,
		deadline = self.drawDeadline,
		serverTime = now(),
		pendingChallenge = nil,
		openingPick = nil,
	}
	if self.pendingChallenge and meIdx == self.pendingChallenge.defenderIdx then
		state.pendingChallenge = {
			offenderId = self.players[self.pendingChallenge.offenderIdx].userId,
			deadline = self.pendingChallenge.deadline,
		}
	end
	if self.openingPick and meIdx == self.openingPick.idx then
		state.openingPick = {
			deadline = self.openingPick.deadline,
		}
	end
	if self.roundResult then
		state.roundResult = self.roundResult
	end
	if self.gameResult then
		state.gameResult = self.gameResult
	end
	return state
end

function Game:broadcast()
	for _, p in ipairs(self.players) do
		if p.connected then
			local plr = game.Players:GetPlayerByUserId(p.userId)
			if plr and plr.Parent then
				self.remotes.StateUpdate:FireClient(plr, self:serializeFor(p.userId))
			end
		end
	end
end

function Game:sendNotice(userId, text, kind)
	local plr = game.Players:GetPlayerByUserId(userId)
	if plr and plr.Parent then
		self.remotes.Notice:FireClient(plr, { text = text, kind = kind or "info" })
	end
end

function Game:toastAll(text, kind)
	for _, p in ipairs(self.players) do
		if p.connected then
			self:sendNotice(p.userId, text, kind)
		end
	end
end

-- ------------------------- deck -------------------------

function Game:drawCards(count)
	local drawn = {}
	for _ = 1, count do
		if #self.deck == 0 then
			self:_reshuffleDiscard()
			if #self.deck == 0 then
				break
			end
		end
		table.insert(drawn, table.remove(self.deck))
	end
	return drawn
end

function Game:_reshuffleDiscard()
	if #self.discard <= 1 then
		return
	end
	local top = table.remove(self.discard)
	self.deck = Rules.shuffle(self.discard, self.rng)
	self.discard = { top }
end

-- If the draw pile is exhausted, the discard holds only the top card, and NO player
-- can legally play a card, the round cannot advance under the official rules.
-- Redeal the round (scores preserved); this mirrors how physical UNO tables agree
-- to reshuffle and restart.
function Game:_resolveStall(idx)
	if self.phase ~= "playing" or #self.deck > 0 or #self.discard > 1 then
		return false
	end
	for _, p in ipairs(self.players) do
		if p.connected then
			for _, c in ipairs(p.hand) do
				if Rules.canPlay(c, self.topCard, self.currentColor) then
					return false
				end
			end
		end
	end
	self:toastAll("No moves possible and the draw pile is empty — redealing the round.")
	self:startRound()
	return true
end

function Game:giveCards(idx, count)
	local p = self.players[idx]
	if not p or not p.connected then
		return 0
	end
	local drawn = self:drawCards(count)
	for _, c in ipairs(drawn) do
		table.insert(p.hand, c)
	end
	return #drawn
end

-- ------------------------- round setup -------------------------

function Game:_flipFirstCard()
	while #self.deck > 0 do
		local c = table.remove(self.deck)
		if c.kind ~= "wilddrawfour" then
			return c
		end
		table.insert(self.deck, 1, c)
	end
	return nil
end

function Game:startRound()
	local live = self:getLiveCount()
	if live < Config.MinPlayers then
		return false
	end

	if #self.deck == 0 then
		self.deck = Rules.shuffle(CardDefs.buildDeck(), self.rng)
	end
	self.discard = {}
	for _, p in ipairs(self.players) do
		if p.connected then
			p.hand = {}
		end
		p.unoCalled = false
		p.catchable = false
	end

	for i, p in ipairs(self.players) do
		if p.connected then
			local drawn = self:drawCards(Config.StartingHandSize)
			for _, c in ipairs(drawn) do
				table.insert(p.hand, c)
			end
		end
	end

	-- Clear leftover per-player data.
	self.pendingChallenge = nil
	self.wild4PriorColor = nil
	self.openingPick = nil
	self.roundResult = nil
	self.gameResult = nil
	self.phase = "playing"

	-- Flip first card (Wild Draw Four is returned to the deck and re-flipped).
	local flipped = self:_flipFirstCard()
	if flipped then
		table.insert(self.discard, flipped)
	end
	self.topCard = flipped or { kind = "number", color = CardDefs.Colors[1], value = 0 }
	if not flipped then
		table.insert(self.discard, self.topCard)
	end

	-- Dealer rotates each round.
	self.dealerIdx = self:step(self.dealerIdx)
	self.direction = 1

	-- Apply first-card effects.
	local startIdx = self:step(self.dealerIdx)
	local tk = self.topCard.kind
	if tk == "skip" then
		startIdx = self:step(startIdx)
		self:toastAll("First card is SKIP! The starting player is skipped.")
	elseif tk == "reverse" then
		self.direction = -1
		startIdx = self.dealerIdx
		self:toastAll("First card is REVERSE! Dealer plays first, going right.")
	elseif tk == "drawtwo" then
		local victim = startIdx
		self:giveCards(victim, 2)
		startIdx = self:step(victim)
		self:toastAll("First card is +2! " .. self.players[victim].name .. " draws 2 and is skipped.")
	elseif tk == "wild" then
		self.currentIdx = startIdx
		self.currentColor = nil
		self.hasDrawn = false
		self.drewCard = nil
		self.openingPick = { idx = startIdx, deadline = now() + Config.OpeningChoiceTime }
		self.drawDeadline = self.openingPick.deadline
		self:toastAll("First card is WILD! " .. self.players[startIdx].name .. " picks the color to play.")
		self:broadcast()
		return true
	else
		self.currentColor = self.topCard.color
	end

	self.currentIdx = startIdx
	self.hasDrawn = false
	self.drewCard = nil
	self.currentColor = self.currentColor or self.topCard.color
	self.drawDeadline = now() + Config.TurnTime
	self:toastAll(self.players[self.dealerIdx].name .. " is dealer. " .. self.players[startIdx].name .. " starts!")
	self:broadcast()
	return true
end

-- ------------------------- turn flow -------------------------

function Game:tick()
	local t = now()

	if self.phase == "playing" then
		if self.openingPick and t >= self.openingPick.deadline then
			local idx = self.openingPick.idx
			self.openingPick = nil
			self.currentColor = CardDefs.Colors[1]
			self:toastAll("Color pick timed out — Red chosen automatically.")
			self:startTurn(idx)
			return
		end

		if self.pendingChallenge and t >= self.pendingChallenge.deadline then
			local ch = self.pendingChallenge
			self.pendingChallenge = nil
			self.wild4PriorColor = nil
			self.drawDeadline = 0
			self:giveCards(ch.defenderIdx, 4)
			self:toastAll(self.players[ch.defenderIdx].name .. " didn't challenge — draws 4.")
			self.currentIdx = self:plainAdvance(ch.defenderIdx)
			self:startTurn(self.currentIdx)
			return
		end

		local idx = self.currentIdx
		if idx and t >= self.drawDeadline and self.players[idx].connected then
			local p = self.players[idx]
			if self.hasDrawn then
				self:passTurn(idx)
			else
				local drawn = self:drawCards(1)
				if #drawn == 0 then
					if not self:_resolveStall(idx) then
						self:toastAll("No cards to draw — turn passes.")
						self:passTurn(idx)
					end
				else
					self.hasDrawn = true
					self.drewCard = drawn[1]
					table.insert(p.hand, 1, drawn[1])
					self:toastAll("Time's up! " .. p.name .. " auto-drew a card.")
					if Rules.canPlay(self.drewCard, self.topCard, self.currentColor) then
						self.drawDeadline = t + Config.PostDrawGrace
						self:broadcast()
					else
						self:passTurn(idx)
					end
				end
			end
		end
	end

	if self.phase == "roundEnd" and t >= self.stateDeadline then
		self.roundResult = nil
		if self:getLiveCount() < Config.MinPlayers then
			self:returnToLobby()
		else
			self:startRound()
		end
	end

	if self.phase == "gameOver" and t >= self.stateDeadline then
		self:returnToLobby()
	end
end

-- Called after a card (or the opening non-action card) is resolved.
function Game:afterPlayAdvance(offenderIdx)
	if self.currentIdx ~= nil then
		self.currentIdx = nil
	end
	self.hasDrawn = false
	self.drewCard = nil
	self.drawDeadline = 0

	local card = self.topCard
	local n = #self.players
	local twoPlayers = n == 2

	if card.kind == "reverse" then
		if twoPlayers then
			self.currentIdx = offenderIdx -- acts like a Skip
		else
			self.direction = -self.direction
			self.currentIdx = self:step(offenderIdx)
		end
	elseif card.kind == "skip" then
		if twoPlayers then
			self.currentIdx = offenderIdx
		else
			self.currentIdx = self:step(self:step(offenderIdx))
		end
	elseif card.kind == "drawtwo" then
		local victim = self:step(offenderIdx)
		self:giveCards(victim, 2)
		self:toastAll(self.players[victim].name .. " draws 2 and loses their turn.")
		if twoPlayers then
			self.currentIdx = offenderIdx
		else
			self.currentIdx = self:step(victim)
		end
	elseif card.kind == "wilddrawfour" then
		local victim = self:step(offenderIdx)
		if twoPlayers then
			self:giveCards(victim, 4)
			self:toastAll(self.players[victim].name .. " draws 4 and loses their turn.")
			self.currentIdx = offenderIdx
		else
			self.pendingChallenge = {
				offenderIdx = offenderIdx,
				defenderIdx = victim,
				deadline = now() + Config.Wild4ChallengeTime,
			}
			self.drawDeadline = self.pendingChallenge.deadline
			self:toastAll(self.players[victim].name .. " may CHALLENGE the WILD +4!")
			self:broadcast()
			return
		end
	else
		self.currentIdx = self:step(offenderIdx)
	end

	-- Wild cards carry no color; currentColor was chosen by the player and must persist.
	if self.topCard.color then
		self.currentColor = self.topCard.color
	end
	self:startTurn(self.currentIdx)
end

-- Move the turn forward by `steps` taking direction into account, for >2 players.
-- In two-player play a skip keeps the same player active.
function Game:plainAdvance(idx)
	local twoPlayers = #self.players == 2
	if twoPlayers then
		return idx
	end
	return self:step(idx)
end

function Game:startTurn(idx)
	if idx == nil then
		self:broadcast()
		return
	end
	self.currentIdx = idx
	self.hasDrawn = false
	self.drewCard = nil
	self.drawDeadline = now() + Config.TurnTime
	-- A missed UNO call can only be caught before the next player begins their turn.
	-- Once this player starts, every other 1-card player's catch window closes.
	for i, p in ipairs(self.players) do
		if i ~= idx and p.catchable and #p.hand == 1 and not p.unoCalled then
			p.catchable = false
		end
	end
	self:toastAll("It's " .. self.players[idx].name .. "'s turn.", "turn")
	self:broadcast()
end

-- ------------------------- actions -------------------------

function Game:handleAction(player, action)
	local userId = player.UserId
	local kind = action.type
	if kind == "start" then
		self:hostStart()
	elseif kind == "setCapacity" then
		self:setCapacity(userId, action.n)
	elseif kind == "play" then
		self:playCard(userId, action)
	elseif kind == "draw" then
		self:drawCard(userId)
	elseif kind == "uno" then
		self:callUno(userId)
	elseif kind == "catch" then
		self:catchUno(userId, action.targetId)
	elseif kind == "challenge" then
		self:resolveChallenge(userId, action.accept)
	elseif kind == "openingColor" then
		self:chooseOpeningColor(userId, action.color)
	elseif kind == "nextRound" then
		self:hostNextRound(userId)
	end
end

function Game:requireHost(userId)
	return self:hostUser() == userId
end

function Game:hostStart()
	if self.phase ~= "lobby" then
		return
	end
	if self:getLiveCount() < Config.MinPlayers then
		local first = self.players[1]
		if first then
			self:sendNotice(first.userId, "Need at least " .. Config.MinPlayers .. " players to start.", "error")
		end
		return
	end
	self:startRound()
end

function Game:setCapacity(userId, n)
	if not self:requireHost(userId) then
		return
	end
	n = tonumber(n) or Config.DefaultCapacity
	n = math.clamp(math.floor(n), Config.MinPlayers, Config.MaxPlayers)
	if n < #self.players then
		self:sendNotice(userId, "Capacity can't be lower than the current player count.", "error")
		return
	end
	self.capacity = n
	self:broadcast()
end

function Game:chooseOpeningColor(userId, color)
	if not self.openingPick then
		return
	end
	local idx = self.openingPick.idx
	local p = self.players[idx]
	if p.userId ~= userId then
		self:sendNotice(userId, "Not your color choice.", "error")
		return
	end
	if not validateColor(color) then
		self:sendNotice(userId, "Invalid color.", "error")
		return
	end
	self.openingPick = nil
	self.currentColor = color
	self:toastAll(p.name .. " picked " .. color .. "!")
	self:startTurn(idx)
end

function Game:playCard(userId, action)
	if self.phase ~= "playing" then
		return
	end
	if self.openingPick or self.pendingChallenge then
		self:sendNotice(userId, "Not time to play yet.", "error")
		return
	end
	local idx, p = self:findPlayer(userId)
	if not idx or self.currentIdx ~= idx or not p.connected then
		self:sendNotice(userId, "It isn't your turn.", "error")
		return
	end
	if self.hasDrawn and self.drewCard and action.cardId ~= self.drewCard.id then
		self:sendNotice(userId, "After drawing you may only play the drawn card.", "error")
		return
	end

	local cardIdx = nil
	local card = nil
	for i, c in ipairs(p.hand) do
		if c.id == action.cardId then
			card = c
			cardIdx = i
			break
		end
	end
	if not card then
		self:sendNotice(userId, "Card not in hand.", "error")
		return
	end
	if not Rules.canPlay(card, self.topCard, self.currentColor) then
		self:sendNotice(userId, "That card can't be played on " .. CardDefs.cardName(self.topCard) .. ".", "error")
		return
	end
	if (card.kind == "wild" or card.kind == "wilddrawfour") and not validateColor(action.color) then
		self:sendNotice(userId, "Choose a color for that card.", "error")
		return
	end

	table.remove(p.hand, cardIdx)
	table.insert(self.discard, card)
	self.topCard = card
	if card.kind == "wilddrawfour" then
		-- Legality (for a later challenge) is judged against the color in play BEFORE this card.
		self.wild4PriorColor = self.currentColor
	end
	if card.kind == "wild" or card.kind == "wilddrawfour" then
		self.currentColor = action.color
	else
		self.currentColor = card.color
	end
	if self.drewCard then
		self.drewCard = nil
	end

	if #p.hand == 1 then
		p.unoCalled = false
		p.catchable = true
		self:sendNotice(userId, "ONE card left — press UNO before you get caught!", "warn")
		self:toastAll(p.name .. " is down to one card!", "warn")
	end

	if #p.hand == 0 then
		self:finishRound(idx, card)
		return
	end

	self:afterPlayAdvance(idx)
end

-- A turn ends by passing (drew nothing, or drew an unplayable card). The action
-- effect of the top card was already resolved when it was played — the turn simply
-- advances to the next player in the current direction.
function Game:passTurn(idx)
	self.currentIdx = nil
	self.hasDrawn = false
	self.drewCard = nil
	self.drawDeadline = 0
	local next = self:step(idx)
	self.currentColor = self.topCard.color or self.currentColor
	self:startTurn(next)
end

function Game:drawCard(userId)
	if self.phase ~= "playing" then
		return
	end
	if self.openingPick or self.pendingChallenge then
		self:sendNotice(userId, "Not time to draw.", "error")
		return
	end
	local idx, p = self:findPlayer(userId)
	if not idx or self.currentIdx ~= idx or not p.connected then
		self:sendNotice(userId, "It isn't your turn.", "error")
		return
	end
	if self.hasDrawn then
		self:sendNotice(userId, "You already drew.", "error")
		return
	end
	self.hasDrawn = true
	local drawn = self:drawCards(1)
	if #drawn == 0 then
		local rr = self:_resolveStall(idx)
		if not rr then
			self:passTurn(idx)
		end
		return
	end
	self.drewCard = drawn[1]
	table.insert(p.hand, 1, drawn[1])
	if Rules.canPlay(self.drewCard, self.topCard, self.currentColor) then
		self.drawDeadline = now() + Config.PostDrawGrace
		self:sendNotice(userId, "You drew " .. CardDefs.cardName(self.drewCard) .. " — playable this turn.", "warn")
		self:broadcast()
	else
		self:sendNotice(userId, "Drew " .. CardDefs.cardName(self.drewCard) .. " — turn ends.", "warn")
		self:passTurn(idx)
	end
end

function Game:callUno(userId)
	local _, p = self:findPlayer(userId)
	if not p then
		return
	end
	if #p.hand ~= 1 then
		self:sendNotice(userId, "You can only call UNO with one card left.", "error")
		return
	end
	p.unoCalled = true
	p.catchable = false
	self:toastAll(p.name .. " called UNO!", "info")
	self:broadcast()
end

function Game:catchUno(userId, targetUserId)
	local tIdx, target = self:findPlayer(targetUserId)
	if not tIdx or target.userId == userId then
		self:sendNotice(userId, "Invalid target.", "error")
		return
	end
	if #target.hand ~= 1 or target.unoCalled or not target.catchable then
		self:sendNotice(userId, target.name .. " isn't catchable right now.", "error")
		return
	end
	local _, who = self:findPlayer(userId)
	target.unoCalled = false
	target.catchable = false
	self:giveCards(tIdx, 2)
	self:toastAll(who.name .. " caught " .. target.name .. " without UNO! +2 cards.", "info")
	self:broadcast()
end

function Game:resolveChallenge(userId, accept)
	if not self.pendingChallenge then
		return
	end
	local ch = self.pendingChallenge
	local defender = self.players[ch.defenderIdx]
	local offender = self.players[ch.offenderIdx]
	if defender.userId ~= userId then
		self:sendNotice(userId, "Only the +4 target can challenge.", "error")
		return
	end
	self.pendingChallenge = nil
	self.drawDeadline = 0
	local priorColor = self.wild4PriorColor or self.topCard.color
	self.wild4PriorColor = nil

	if accept then
		if Rules.hasColorMatch(offender.hand, priorColor) then
			self:giveCards(ch.offenderIdx, 4)
			self:toastAll("Challenge SUCCEEDED! " .. offender.name .. " drew the +4 illegally and takes it instead.")
			self.currentIdx = ch.defenderIdx -- play continues with the challenger
		else
			self:giveCards(ch.defenderIdx, 6)
			self:toastAll("Challenge FAILED! " .. defender.name .. " must draw 6 cards.")
			self.currentIdx = self:plainAdvance(ch.defenderIdx)
		end
	else
		self:giveCards(ch.defenderIdx, 4)
		self:toastAll(defender.name .. " accepts the +4 and draws 4.")
		self.currentIdx = self:plainAdvance(ch.defenderIdx)
	end
	self:startTurn(self.currentIdx)
end

function Game:hostNextRound(userId)
	if self.phase ~= "roundEnd" then
		return
	end
	if not self:requireHost(userId) then
		return
	end
	self.roundResult = nil
	if self:getLiveCount() < Config.MinPlayers then
		self:returnToLobby()
	else
		self:startRound()
	end
end

function Game:finishRound(winnerIdx, winningCard)
	self.pendingChallenge = nil
	self.wild4PriorColor = nil
	self.openingPick = nil
	self.drawDeadline = 0
	self.deck = {} -- next round deals from a fresh, reshuffled deck

	-- If the last card is a Draw Two / Wild Draw Four, the next player draws first.
	local nextIdx = self:step(winnerIdx)
	if winningCard.kind == "drawtwo" then
		self:giveCards(nextIdx, 2)
	elseif winningCard.kind == "wilddrawfour" then
		self:giveCards(nextIdx, 4)
	end

	local winner = self.players[winnerIdx]
	local roundPoints = 0
	local ledger = {}
	for i, p in ipairs(self.players) do
		if i ~= winnerIdx and p.connected then
			local pts = Rules.totalPoints(p.hand)
			if pts > 0 then
				roundPoints += pts
				table.insert(ledger, { name = p.name, points = pts })
			end
		end
	end
	winner.score += roundPoints
	self.roundResult = {
		winnerId = winner.userId,
		winnerName = winner.name,
		winnerScore = winner.score,
		roundPoints = roundPoints,
		ledger = ledger,
	}

	if Config.WinByFirstOut or winner.score >= Config.TargetScore then
		self.phase = "gameOver"
		self.gameResult = {
			winnerId = winner.userId,
			winnerName = winner.name,
			winnerScore = winner.score,
			players = self:publicPlayersForResult(),
		}
		self.stateDeadline = now() + Config.GameOverTime
		self:toastAll(winner.name .. " reached " .. winner.score .. " points and WINS THE GAME!", "gameover")
	else
		self.phase = "roundEnd"
		self.stateDeadline = now() + Config.RoundResultTime
		self:toastAll(winner.name .. " wins the round! +" .. roundPoints .. " points.", "roundend")
	end
	self:broadcast()
end

function Game:publicPlayersForResult()
	local out = {}
	for _, p in ipairs(self.players) do
		table.insert(out, self:publicPlayer(p))
	end
	return out
end

-- ------------------------- join / leave -------------------------

function Game:addLobbyPlayer(userId, name)
	if self.phase ~= "lobby" or self:findPlayer(userId) then
		return self:findPlayer(userId) ~= nil
	end
	if self:getLiveCount() >= self.capacity then
		return false
	end
	table.insert(self.players, {
		userId = userId,
		name = name,
		isHost = #self.players == 0,
		hand = {},
		score = 0,
		unoCalled = false,
		catchable = false,
		connected = true,
	})
	self:broadcast()
	return true
end

function Game:onPlayerLeave(userId)
	local idx, p = self:findPlayer(userId)
	if not idx then
		return
	end
	p.connected = false

	if self.phase == "lobby" then
		table.remove(self.players, idx)
		if #self.players > 0 then
			self.players[1].isHost = true
		end
		self:broadcast()
		return
	end

	-- Abort during an active game if < 2 live players.
	if self:getLiveCount() < Config.MinPlayers then
		table.remove(self.players, idx)
		if self.players[1] then
			self.players[1].isHost = true
		end
		self:returnToLobby()
		return
	end

	local wasCurrent = idx == self.currentIdx
	local wasPicking = self.openingPick and self.openingPick.idx == idx
	local wasInChallenge = self.pendingChallenge and
		(self.pendingChallenge.offenderIdx == idx or self.pendingChallenge.defenderIdx == idx)

	p.hand = {}

	table.remove(self.players, idx)

	if self.players[1] then
		self.players[1].isHost = true
	end

	-- Reindex pending pointers.
	if self.pendingChallenge then
		if self.pendingChallenge.offenderIdx > idx then
			self.pendingChallenge.offenderIdx -= 1
		end
		if self.pendingChallenge.defenderIdx > idx then
			self.pendingChallenge.defenderIdx -= 1
		end
	end
	if self.openingPick and self.openingPick.idx > idx then
		self.openingPick.idx -= 1
	end
	if self.dealerIdx > idx then
		self.dealerIdx -= 1
	end

	if wasInChallenge then
		-- Cancel the pending challenge gracefully; pass to the next live player.
		self.pendingChallenge = nil
		self.wild4PriorColor = nil
		self.drawDeadline = 0
		self:startTurn(self:plainAdvance(math.clamp(idx, 1, #self.players)))
	elseif wasPicking then
		self.openingPick = nil
		self.currentColor = CardDefs.Colors[1]
		self:afterPlayAdvance(math.clamp(idx, 1, #self.players))
	else
		self:_resumeTurnAfterLeave(idx, wasCurrent)
	end

	self:broadcast()
end

function Game:_resumeTurnAfterLeave(removedIdx, wasCurrent)
	if not self.currentIdx then
		return
	end
	if self.currentIdx > removedIdx then
		self.currentIdx -= 1
	end
	if self.currentIdx > #self.players then
		self.currentIdx = 1
	end
	self.currentIdx = math.clamp(self.currentIdx, 1, #self.players)

	if wasCurrent then
		-- Removed player had the turn; pass it to the next live player in order.
		self.currentIdx = self:step(self.currentIdx)
	end
	if self.currentIdx < 1 or self.currentIdx > #self.players then
		self.currentIdx = 1
	end
	while self.currentIdx and not self.players[self.currentIdx].connected do
		self.currentIdx = self:step(self.currentIdx)
	end
	self.hasDrawn = false
	self.drewCard = nil
	self.drawDeadline = now() + Config.TurnTime
	self:broadcast()
end

function Game:returnToLobby()
	self.phase = "lobby"
	self.currentIdx = nil
	self.topCard = nil
	self.currentColor = nil
	self.deck = {}
	self.discard = {}
	self.pendingChallenge = nil
	self.wild4PriorColor = nil
	self.openingPick = nil
	self.roundResult = nil
	self.gameResult = nil
	self.hasDrawn = false
	self.drewCard = nil
	self.drawDeadline = 0
	for i, p in ipairs(self.players) do
		if p.connected then
			p.hand = {}
			p.score = 0
		end
		if i == 1 then
			p.isHost = true
		end
	end
	self:broadcast()
end

return Game
]====]
BUNDLE["Json"] = [====[
-- Minimal JSON encode/decode for the web engine sidecar (luau CLI has no JSON).
-- Handles the primitives/tables used by the UNO engine: numbers, strings,
-- booleans, nil, and nested tables (arrays + objects). Not for hostile input.

local Json = {}

local ESCAPES = {
	['"'] = '\\"',
	["\\"] = "\\\\",
	["\b"] = "\\b",
	["\f"] = "\\f",
	["\n"] = "\\n",
	["\r"] = "\\r",
	["\t"] = "\\t",
}

local function encodeString(s)
	local out = { '"' }
	for i = 1, #s do
		local c = s:sub(i, i)
		if ESCAPES[c] then
			out[#out + 1] = ESCAPES[c]
		else
			local b = s:byte(i)
			if b < 32 then
				out[#out + 1] = string.format("\\u%04x", b)
			else
				out[#out + 1] = c
			end
		end
	end
	out[#out + 1] = '"'
	return table.concat(out)
end

local function isArray(t)
	local n = #t
	for k in pairs(t) do
		if type(k) ~= "number" or k < 1 or k > n or k ~= math.floor(k) then
			return false
		end
	end
	return true
end

function Json.encode(v)
	local t = type(v)
	if t == "nil" then
		return "null"
	elseif t == "number" then
		if v ~= v or v == math.huge or v == -math.huge then
			return "null"
		end
		if v == math.floor(v) and math.abs(v) < 1e15 then
			return string.format("%d", v)
		end
		return string.format("%.12g", v)
	elseif t == "boolean" then
		return tostring(v)
	elseif t == "string" then
		return encodeString(v)
	elseif t == "table" then
		local parts = {}
		if isArray(v) then
			for i = 1, #v do
				parts[#parts + 1] = Json.encode(v[i])
			end
			return "[" .. table.concat(parts, ",") .. "]"
		else
			for k, val in pairs(v) do
				if type(k) == "string" then
					parts[#parts + 1] = encodeString(k) .. ":" .. Json.encode(val)
				end
			end
			table.sort(parts)
			return "{" .. table.concat(parts, ",") .. "}"
		end
	end
	error("cannot json-encode type " .. t, 2)
end

-- --- decoder ----------------------------------------------------------------

local function decodeValue(s, i)
	while i <= #s and s:sub(i, i):find("%s") do
		i += 1
	end
	local c = s:sub(i, i)
	if c == "{" then
		local obj = {}
		i += 1
		while true do
			while i <= #s and s:sub(i, i):find("%s") do
				i += 1
			end
			c = s:sub(i, i)
			if c == "}" then
				return obj, i + 1
			end
			if c ~= '"' then
				error("expected object key at " .. i)
			end
			local key, j = decodeValue(s, i)
			while j <= #s and s:sub(j, j):find("%s") do
				j += 1
			end
			if s:sub(j, j) ~= ":" then
				error("expected : at " .. j)
			end
			local val, k = decodeValue(s, j + 1)
			obj[key] = val
			i = k
			while i <= #s and s:sub(i, i):find("%s") do
				i += 1
			end
			if s:sub(i, i) == "," then
				i += 1
			elseif s:sub(i, i) ~= "}" then
				error("expected , or } at " .. i)
			end
		end
	elseif c == "[" then
		local arr = {}
		local n = 0
		i += 1
		while true do
			while i <= #s and s:sub(i, i):find("%s") do
				i += 1
			end
			c = s:sub(i, i)
			if c == "]" then
				return arr, i + 1
			end
			local val, j = decodeValue(s, i)
			n += 1
			arr[n] = val
			i = j
			while i <= #s and s:sub(i, i):find("%s") do
				i += 1
			end
			if s:sub(i, i) == "," then
				i += 1
			elseif s:sub(i, i) ~= "]" then
				error("expected , or ] at " .. i)
			end
		end
	elseif c == '"' then
		local out = {}
		i += 1
		while true do
			local ch = s:sub(i, i)
			if ch == "" or ch == '"' then
				break
			elseif ch == "\\" then
				local esc = s:sub(i + 1, i + 1)
				if esc == "u" then
					local hex = s:sub(i + 2, i + 5)
					local cp = tonumber("0x" .. hex)
					table.insert(out, utf8.char(cp))
					i += 6
				else
					local map = { ['"'] = '"', ["\\"] = "\\", ["/"] = "/", ["b"] = "\b", ["f"] = "\f", ["n"] = "\n", ["r"] = "\r", ["t"] = "\t" }
					table.insert(out, map[esc] or esc)
					i += 2
				end
			else
				table.insert(out, ch)
				i += 1
			end
		end
		return table.concat(out), i + 1
	elseif c == "t" then
		if s:sub(i, i + 3) == "true" then
			return true, i + 4
		end
		error("bad literal at " .. i)
	elseif c == "f" then
		if s:sub(i, i + 4) == "false" then
			return false, i + 5
		end
		error("bad literal at " .. i)
	elseif c == "n" then
		if s:sub(i, i + 3) == "null" then
			return nil, i + 4
		end
		error("bad literal at " .. i)
	elseif c == "-" or (c and c:byte() and c:byte() >= 48 and c:byte() <= 57) then
		local start, fini = s:find("[%d%.eE+-]+", i)
		local tok = s:sub(start, fini)
		local num = tonumber(tok)
		return num, fini + 1
	end
	error("unexpected char '" .. c .. "' at " .. i)
end

function Json.decode(s)
	local v = decodeValue(s, 1)
	return v
end

return Json
]====]
-- bridge_body.lua: web sidecar runtime, appended after the BUNDLE defs by
-- gen_bundle.sh. Runs the UNO engine inside the luau-web WASM VM and exposes a
-- single RPC entry: __rpc.dispatch(jsonRequest) -> jsonResponse (JSON strings).
-- The engine's Roblox touches (game/workspace/require/remotes) are shimmed so
-- the game logic is byte-for-byte identical to the Roblox + headless builds.

-- --- Roblox-like environment ------------------------------------------------
local clockValue = 0
liveUsers = {} -- userId -> true; which users the engine may broadcast to

Color3 = {
	fromRGB = function(_, r, g, b) return { r = r, g = g, b = b } end,
	new = function() return {} end,
}
Random = {
	new = function()
		return {
			NextInteger = function(_, a, b) return math.random(a, b) end,
		}
	end,
}
if os and os.time then
	math.randomseed(os.time() % 2147483647)
end

local fakeWorkspace = {
	GetServerTimeNow = function()
		return clockValue
	end,
}
local fakePlayers = {
	GetPlayerByUserId = function(_, uid)
		if liveUsers[uid] then
			return { UserId = uid, Parent = true }
		end
		return nil
	end,
}
local fakeReplicatedStorage = { UNO = { Config = {}, CardDefs = {}, Rules = {} } }
game = {
	GetService = function(_, name)
		if name == "ReplicatedStorage" then
			return fakeReplicatedStorage
		elseif name == "Workspace" then
			return fakeWorkspace
		elseif name == "Players" then
			return fakePlayers
		end
		error("unexpected GetService: " .. tostring(name))
	end,
	Players = fakePlayers,
	Workspace = fakeWorkspace,
	ReplicatedStorage = fakeReplicatedStorage,
}
workspace = fakeWorkspace
script = { Parent = { CardDefs = fakeReplicatedStorage.UNO.CardDefs } }
Players = fakePlayers
ReplicatedStorage = fakeReplicatedStorage

-- --- module loading (needs a JS-backed global `loadstring`) ------------------
local mapping = {} -- instance table -> module
loaded = {}
require = function(m)
	if typeof(m) == "table" then
		if mapping[m] then
			return mapping[m]
		end
		error("unmapped instance passed to require: " .. tostring(m), 2)
	end
	error("bad require argument", 2)
end

local function loadModule(name)
	if loaded[name] then
		return loaded[name]
	end
	local fn = loadstring(BUNDLE[name], "=" .. name)
	if not fn then
		error("failed to load module " .. name)
	end
	local ok, mod = pcall(fn)
	if not ok then
		error("failed to init module " .. name .. ": " .. tostring(mod))
	end
	loaded[name] = mod
	return mod
end

local confMod = loadModule("Config")
local cardMod = loadModule("CardDefs")
mapping[fakeReplicatedStorage.UNO.Config] = confMod
mapping[fakeReplicatedStorage.UNO.CardDefs] = cardMod
local rulesMod = loadModule("Rules")
mapping[fakeReplicatedStorage.UNO.Rules] = rulesMod
local GameMod = loadModule("Game")
local Json = loadModule("Json")

-- --- RPC plumbing -----------------------------------------------------------
local sessions = {} -- gid -> Game instance
LUA__outbox = {} -- events gathered during the current request

local function withOutbox(var)
	LUA__outbox = var or {}
	return LUA__outbox
end

-- each handler: (sess, req) and may push into LUA__outbox
local handlers = {}

-- create: {"players":[{"userId":..,"name":..}], "capacity":..}
handlers.create = function(_sess, req)
	local roster = {}
	for _, p in ipairs(req.players) do
		table.insert(roster, { userId = p.userId, name = p.name })
		liveUsers[p.userId] = true
	end
	local remotes = {
		StateUpdate = {
			FireClient = function(_, plr, st)
				table.insert(LUA__outbox, { kind = "state", userId = plr.UserId, state = st })
			end,
		},
		Notice = {
			FireClient = function(_, plr, data)
				table.insert(LUA__outbox, { kind = "notice", userId = plr.UserId, notice = data })
			end,
		},
	}
	local g = GameMod.new(roster, remotes)
	g.capacity = req.capacity or 4
	return g
end

-- join: {"userId":.., "name":..}
handlers.join = function(sess, req)
	liveUsers[req.userId] = true
	sess:addLobbyPlayer(req.userId, req.name)
end

-- leave: {"userId":..}
handlers.leave = function(sess, req)
	liveUsers[req.userId] = nil
	sess:onPlayerLeave(req.userId)
end

-- action: {"userId":.., "action":{...}} -- mirrors the Roblox Action remote
handlers.action = function(sess, req)
	sess:handleAction({ UserId = req.userId, Name = "" }, req.action)
end

-- tick: {} -- heartbeat; the Node side supplies `t` in the request
handlers.tick = function(sess, _req)
	sess:tick()
end

-- sync: {"userId":..} -- full state push for a (re)connecting client
handlers.sync = function(sess, req)
	local st = sess:serializeFor(req.userId)
	if st then
		table.insert(LUA__outbox, { kind = "state", userId = req.userId, state = st })
	end
end

-- dispatch(jsonRequest) -> jsonResponse
-- request:  {"t":<clock>, "gid":<string>, "op":<string>, ...}
-- response: {"ok":bool, "gid":<string>, "events":[{"kind":"state|notice","userId":..,"state"?:..,"notice"?:..}]}
__rpc = {}
__rpc.dispatch = function(requestJson)
	local req = Json.decode(requestJson)
	if type(req.t) == "number" then
		clockValue = math.max(clockValue, req.t)
	end
	withOutbox({})
	local ok = true
	local err = nil
	local gid = req.gid
	local sess = sessions[gid]
	local created = false
	if req.op == "create" then
		local pres, res = pcall(handlers.create, nil, req)
		if pres then
			sess = res
			sessions[gid] = sess
		else
			ok = false
			err = tostring(res)
		end
	else
		if not sess then
			ok = false
			err = "unknown game: " .. tostring(gid)
		else
			local h = handlers[req.op]
			if not h then
				ok = false
				err = "unknown op: " .. tostring(req.op)
			else
				local pres, res = pcall(h, sess, req)
				if not pres then
					ok = false
					err = tostring(res)
				end
			end
		end
	end
	-- broadcast after any successful mutation so all connected users resync
	if ok and sess and req.op ~= "sync" then
		local pcfg = pcall(function()
			sess:broadcast()
		end)
		if not pcfg then
			ok = false
			err = "broadcast failed"
		end
	end
	local events = {}
	for _, ev in ipairs(LUA__outbox) do
		local encoded = {
			kind = ev.kind,
			userId = ev.userId,
			state = ev.kind == "state" and Json.encode(ev.state) or nil,
			notice = ev.kind == "notice" and Json.encode(ev.notice) or nil,
		}
		-- drop consecutive duplicates (the engine may broadcast internally AND
		-- the dispatcher re-broadcasts after every op)
		local last = events[#events]
		if last and last.kind == encoded.kind and last.userId == encoded.userId and last.state == encoded.state and last.notice == encoded.notice then
			-- skip
		else
			table.insert(events, encoded)
		end
	end
	return Json.encode({ ok = ok, gid = gid, events = events, error = err })
end

return __rpc